spring.application.name=appointment-backend
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

appointment.availability.workday-start=09:00
appointment.availability.workday-end=18:00
appointment.availability.slot-minutes=30
appointment.availability.working-days=MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY

appointment.notifications.reminder-minutes-before=60
appointment.notifications.reminder-check-ms=60000

