spring.application.name=appointment-backend
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-divine-lab-asmzc24h-pooler.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_ITOv8gYxrXy0

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

